# RT-Thread building script for component
Import('RTT_ROOT')

from building import *

cwd = GetCurrentDir()
group = []
if GetDepend('USE_MA35_AARCH32'):
	src = Glob('*.c') + Glob('*.cpp')
	CPPPATH = [cwd]
	group = DefineGroup('nu_pkgs_nuwriter', src, depend = ['RT_USING_DFS'], CPPPATH = CPPPATH)

Return('group')
